# Generated by Django 5.0.3 on 2025-04-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.CharField(default='Bilgilendirme', max_length=20),
        ),
    ]
