# Generated by Django 5.1.3 on 2025-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Yazar', 'Yazar'), ('Editör', 'Editör'), ('Hakem', 'Hakem')], default='Yazar', max_length=10),
        ),
    ]
