# Generated by Django 5.1.3 on 2025-04-01 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtopic',
        ),
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.CreateModel(
            name='ArticleSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('subtopic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subtopic')),
            ],
            options={
                'unique_together': {('article', 'subtopic')},
            },
        ),
    ]
