# Generated by Django 5.1.3 on 2025-03-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_article_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(upload_to='articles/'),
        ),
    ]
